# Generated by Django 3.2.5 on 2022-05-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_userprofileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(default='', max_length=264)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('face_encode', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
