# Generated by Django 3.2.5 on 2022-05-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20220526_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_pairs',
            name='grp_pic',
            field=models.ImageField(blank=True, default='akhil.jpg', upload_to='profile_pics'),
        ),
    ]
